config/routes.rb
Cbc::Application.routes.draw do
  root to: 'static_pages#bbs'
  
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: 'static_pages#signup'

  match '/bbs', to: 'algo_pages#bbs'
  match '/merges', to: 'algo_pages#merges'
  match '/quicks', to: 'algo_pages#quicks'
  match '/heaps', to: 'algo_pages#heaps'
  match 'radixs', to: 'algo_pages#radixs'

end

app/controllers/algo_pages_controller.rb
class AlgoPagesController < ApplicationController
  def bbs
  end

  def merges
  end

  def heaps
  end

  def quicks
  end

  def radixs
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def play
  end

  def about
  end

  def contact
  end

  def signup
  end

end

app/helpers/algo_pages_helper.rb
module AlgoPagesHelper

	def nav_link(link_text, link_path)
	  class_name = current_page?(link_path) ? 'current' : ''

	  content_tag(:li, :class => class_name) do
	    link_to link_text, link_path
	  end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

	def nav_link(link_text, link_path)
	  class_name = current_page?(link_path) ? 'active' : ''

	  content_tag(:li, :class => class_name) do
	    link_to link_text, link_path
	  end
	end
end

app/views/algo_pages/bbs.html.erb
<%= render 'layouts/algoMenu' %>

<div class="well span7"> <h3> Think you know Bubble sort?</h3>
        <p> Click the green buttons to swap any two sort elements.</p>
        <p> If you match the exact iterative process of a standard bubble sort algorithm, you win!</p>
</div>

<%= javascript_tag "runSort(bubbleSort)" %>

app/views/algo_pages/heaps.html.erb
<%= render 'layouts/algoMenu' %>
<%= render 'layouts/coming-soon' %>

app/views/algo_pages/merges.html.erb
<%= render 'layouts/algoMenu' %>
<%= render 'layouts/coming-soon' %>

app/views/algo_pages/quicks.html.erb
<%= render 'layouts/algoMenu' %>
<%= render 'layouts/coming-soon' %>

app/views/algo_pages/radixs.html.erb
<%= render 'layouts/algoMenu' %>
<%= render 'layouts/coming-soon' %>

app/views/layouts/_array-size-menu.html.erb
<div class="btn-group">
    <a class="btn btn-danger dropdown-toggle" data-toggle="dropdown" href="#">
    	Array Size
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li><a onclick="setMaxSortElements('Big')">Big</a></li>
        <li><a onclick="setMaxSortElements('Medium')">Medium</a></li>
        <li><a onclick="setMaxSortElements('Small')">Small</a></li>
    </ul>
</div>

app/views/layouts/_coming-soon.html.erb
<div class="well span4"><h1> Coming Soon! </h1></div>

app/views/layouts/_header.html.erb
<div class="row-fluid">
    <div class="navbar navbar-inverse navbar-fixed-top span10">
        <div class="navbar-inner">
            <div class="container-fluid">

                <a class="brand" href="#">Concept Before Code</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li><%= link_to "Play", root_path %></li>
                        <li><%= link_to "About", about_path %></li>
                        <li><%= link_to "Contact", contact_path%></li>
                        <li id='signup'><%= link_to "Sign Up", signup_path%></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js" %>
    <%= csrf_meta_tags %>

    <meta http-equiv="no-cache">
    <meta http-equiv="Expires" content="-1">
    <meta http-equiv="Cache-Control" content="no-cache">
    <%= render 'layouts/shim' %>
    <title> Concept Before Code </title>
</head>

<body>
<!--Number of Sort Elements: <input type="text" id="max_sort_text">-->
<!--<button type="button" id="maxSortButton">Refresh</button>-->
<!--<div id="options"><h2 class="optionHeader">Options</h2></div>-->
<!-- <div class="folddown_instructions">
    <p>Click on me, I dare you!</p>
</div> -->

<%= render 'layouts/header' %>

<div class="row-fluid removable" id="playElements">
    <%= yield %>
</div>

</body>
</html>

app/views/static_pages/about.html.erb
<div class="well span5"> <h3> What is Concept Before Code?</h3>
        <p> Often when we are first learning new algorithms we are bombarded by a great deal of text and psuedocode. When I learn new algorithms, I usually bust out a sheet of paper and begin drawing how the data is getting transformed as the algorithm proceeds.

Concept before code is a tool I built so that people who want to test their conceptual knowledge of various algorithms can do so by using a visual, interactive, simulated representation of how the data is transformed as you iterate through the algorithm. This should improve the learning and understanding of the algorithm! </p>
</div>

app/views/static_pages/bbs.html.erb
<%= render 'layouts/algoMenu' %>

<div class="well span7"> <h3> Think you know Bubble sort?</h3>
        <p> Click the green buttons to swap any two sort elements.</p>
        <p> If you match the exact iterative process of a standard bubble sort algorithm, you win!</p>
</div>

<%= javascript_tag "runSort(bubbleSort)" %>

<%= render 'layouts/array-size-menu.html.erb' %>

app/views/static_pages/contact.html.erb
<div class="well span5">
	<h4>Comments/Suggestions? </h4>
	<p>Contact me at <b>theraccoun@gmail.com</b></p>
</div>

app/views/static_pages/play.html.erb
<% provide(:algo, "bubbleSort") %>
<div class="span3">
    <nav>
        <ul class="well nav nav-list">
            <li class="nav-header">Sorting Algorithms</li>
            <li class="divider"></li>
            <li class="active" id="liBubbleSort"><a onclick="toggleActiveSideNav('#liBubbleSort'); runSort(bubbleSort)">
                <i class="icon-chevron-right"></i>Bubble Sort </a>
            </li>
            <li id="liMergeSort"><a onclick="toggleActiveSideNav('#liMergeSort'); runSort(MergeSort)">
                <i class="icon-chevron-right"></i>Merge Sort </a>
            </li>
            <li id="liQuickSort"><a onclick="toggleActiveSideNav('#liQuickSort'); runSort(MergeSort)">
                <i class="icon-chevron-right"></i>Quick Sort </a>
            </li>
            <li id="liHeapSort"><a onclick="toggleActiveSideNav('#liHeapSort'); runSort(MergeSort)">
                <i class="icon-chevron-right"></i>Heap Sort </a>
            </li>
            <li id="liRadixSort"><a onclick="toggleActiveSideNav('#liRadixSort'); runSort(MergeSort)">
                <i class="icon-chevron-right"></i>Radix Sort </a>
            </li>

            <li class="nav-header">Trees and Graphs</li>
            <li class="divider"></li>
            <li id="liBinaryTree"><a onclick="toggleActiveSideNav('#liBinaryTree'); runSort(MergeSort)">
                <i class="icon-chevron-right"></i>Binary Tree</a>
            </li>

        </ul>
    </nav>
</div>

<div class="well span7"> <h3> Think you know Bubble sort?</h3>
        <p> Click the green buttons to swap any two sort elements.</p>
        <p> If you match the exact iterative process of a standard bubble sort algorithm, you win!</p>
</div>

<div class="btn-group">
    <button class="btn btn-danger">Array Size</button>
    <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        <li><a onclick="setMaxSortElements('Big')">Big</a></li>
        <li><a onclick="setMaxSortElements('Medium')">Medium</a></li>
        <li><a onclick="setMaxSortElements('Small')">Small</a></li>
    </ul>
</div>

app/views/static_pages/signup.html.erb
<h1> Coming Soon! </h1>